"""
LEAF v3.4 versioned evaluator (re-certification of the leak corrections).

Design rules taken from the audit brief:
  * EVERY baseline is reported. No "best baseline" is selected after seeing
    test outcomes; comparisons are pre-specified as LEAF v3.4 vs each baseline.
  * Model comparisons use a PAIRED cluster bootstrap by QB, plus a sensitivity
    analysis clustered by SEASON (the T1 target is season-indexed, so QB
    clustering alone can understate between-season dependence).
  * Probabilistic scoring uses FULL predictive intervals: state variance +
    skill-transition variance + target-season sampling noise (finding E).
    All three components are fit on the training era only.
  * Metrics: r, RMSE, MAE, interval coverage at 50/80/90, PIT calibration
    (KS statistic), CRPS, and Gaussian NLL.

Writes docs/LEAF_V34_RECERTIFICATION.md (new file; never touches v3 docs).
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats as sps

ROOT = Path(__file__).parent.parent.parent
PROD = ROOT / 'data' / 'production'
TEST_MIN, TEST_MAX = 2019, 2025
MIN_PLAYS = 150
RNG = np.random.default_rng(20260728)

PREDICTORS = {
    'B1 expanding mean': 'b1_expanding',
    'B2 prev-season EPA': 'b2_prev_season',
    'B3 EWMA': 'b3_ewma',
    'B4 last-12 mean': 'b4_last12',
    'V1 Kalman raw EPA': 'k_epa',
    'V2 Kalman opp-adj': 'k_adj_epa',
    'V3 informed (priors/age)': 'k_informed',
    'LEAF v3.4 (fused)': 'leaf_v34',
}
PRIMARY = 'leaf_v34'


def build_t1(df, rating_cols):
    rows = []
    for pid, g in df.groupby('passer_player_id'):
        seas = g.groupby('season')['plays'].sum()
        for y, p in seas.items():
            if p < MIN_PLAYS or (y + 1) not in seas or seas[y + 1] < MIN_PLAYS:
                continue
            if y + 1 < TEST_MIN or y + 1 > TEST_MAX:
                continue
            gy, gy1 = g[g.season == y], g[g.season == y + 1]
            row = {'passer_player_id': pid, 'y': y, 'target_season': y + 1,
                   'target': np.average(gy1['epa'], weights=gy1['plays']),
                   'target_plays': gy1['plays'].sum(),
                   'state_var': gy['k_informed_var'].iloc[-1]}
            for c in rating_cols:
                row[c] = (np.average(gy['epa'], weights=gy['plays'])
                          if c == 'b2_prev_season' else gy[c].iloc[-1])
            rows.append(row)
    return pd.DataFrame(rows).dropna(subset=list(rating_cols))


# ------------------------------------------------------------- probabilistic
def gaussian_crps(y, mu, sd):
    z = (y - mu) / sd
    return sd * (z * (2 * sps.norm.cdf(z) - 1) + 2 * sps.norm.pdf(z)
                 - 1 / np.sqrt(np.pi))


def prob_scores(d, mu, params):
    pi = params['predictive_interval']
    var = (d['state_var'] + pi['skill_change_var']
           + pi['play_noise_var'] / d['target_plays'])
    sd = np.sqrt(var)
    y = d['target']
    out = {'mean_sd': sd.mean(),
           'CRPS': gaussian_crps(y, mu, sd).mean(),
           'NLL': (-sps.norm.logpdf(y, mu, sd)).mean()}
    for lvl, z in [(50, 0.6745), (80, 1.2816), (90, 1.6449)]:
        out[f'cov{lvl}'] = float(((y >= mu - z * sd) & (y <= mu + z * sd)).mean())
    pit = sps.norm.cdf((y - mu) / sd)
    out['PIT_KS'] = float(sps.kstest(pit, 'uniform').statistic)
    return out, sd


# ------------------------------------------------------------- bootstrap
def paired_boot(d, col_a, col_b, unit, n=2000):
    """Paired cluster bootstrap of r(a) - r(b); clusters resampled together so
    the comparison is paired on identical resamples."""
    units = d[unit].unique()
    by = {u: d[d[unit] == u] for u in units}
    diffs = []
    for _ in range(n):
        pick = RNG.choice(units, len(units), replace=True)
        s = pd.concat([by[u] for u in pick])
        if s[col_a].std() > 0 and s[col_b].std() > 0 and s['target'].std() > 0:
            diffs.append(s[col_a].corr(s['target']) - s[col_b].corr(s['target']))
    return np.percentile(diffs, [2.5, 97.5])


def main():
    params = json.load(open(PROD / 'leaf_v34_params.json'))
    df = pd.read_csv(PROD / 'leaf_v34_ratings.csv')
    d = build_t1(df, list(PREDICTORS.values()))
    print(f'T1 frozen era {TEST_MIN}-{TEST_MAX}: n={len(d)} pairs, '
          f'{d.passer_player_id.nunique()} QBs, {d.target_season.nunique()} seasons')

    L = ['# LEAF v3.4 Re-Certification\n',
         'Generated by `scripts/v3_4/evaluate_v34.py`. This is a NEW document; '
         'v3 results in `docs/LEAF_V3_RESULTS.md` are untouched.\n',
         '## What changed vs v3\n',
         '| Correction | v3 behaviour | v3.4 behaviour |', '|---|---|---|',
         '| A. Fusion label leakage | origin season ≤ 2018 only; 16-game target could run into 2019+ '
         f'({params["fusion"]["n_excluded_for_target_leakage"]} such pairs) | every target game ≤ 2018 |',
         '| A2. Target semantics | "next 16 games" silently meant next 16 APPEARANCES (spans to 12 years) '
         f'| primary fit restricted to spans ≤ {params["fusion"]["max_target_span_days"]}d; long-span variant reported separately |',
         '| B. Opponent adjustment | defense updated after every passer row; league aggregates moved mid-date '
         '| all pre-game states read first; one play-weighted update per game-defense; league aggregates advance at date boundaries |',
         '| C. Population | postseason + non-QB passers mixed in | regular season only, QB only, with a drop report |',
         '| E. Intervals | state variance only | state + skill-transition + target sampling noise, all train-fit |',
         '',
         f'**Population:** {params["population"]}. Base rows: '
         f'{len(pd.read_csv(PROD / "qb_games_base_v34.csv")):,} QB-games '
         f'(v3 used 13,222 incl. postseason and non-QB passers).\n',
         f'**Frozen-era T1 sample:** n = {len(d)} pairs, '
         f'{d.passer_player_id.nunique()} QBs (v3 reported n = 200, 60 QBs on its '
         'own population; sample differs because the population changed).\n',
         '## Point-forecast accuracy — ALL predictors reported\n',
         '| Predictor | r | RMSE | MAE |', '|---|---|---|---|']

    print('\n--- all predictors (no post-hoc selection) ---')
    for name, col in PREDICTORS.items():
        r = d[col].corr(d['target'])
        rmse = np.sqrt(((d[col] - d['target']) ** 2).mean())
        mae = (d[col] - d['target']).abs().mean()
        print(f'  {name:26s} r={r:+.4f}  RMSE={rmse:.4f}  MAE={mae:.4f}')
        L.append(f'| {name} | {r:+.4f} | {rmse:.4f} | {mae:.4f} |')
    L.append('')

    print('\n--- paired cluster bootstrap: LEAF v3.4 vs EVERY baseline ---')
    L.append('## LEAF v3.4 vs every baseline (paired cluster bootstrap, 2000 resamples)\n')
    L.append('No baseline was chosen after seeing outcomes; all are reported.\n')
    L.append('| Comparison | Δr | 95% CI (cluster = QB) | 95% CI (cluster = season) | verdict |')
    L.append('|---|---|---|---|---|')
    for name, col in PREDICTORS.items():
        if col == PRIMARY:
            continue
        dr = d[PRIMARY].corr(d['target']) - d[col].corr(d['target'])
        qlo, qhi = paired_boot(d, PRIMARY, col, 'passer_player_id')
        slo, shi = paired_boot(d, PRIMARY, col, 'target_season')
        sig_qb = qlo > 0 or qhi < 0
        sig_se = slo > 0 or shi < 0
        flag = ('excl. 0 (QB+season)' if sig_qb and sig_se else
                'excl. 0 (season only)' if sig_se else
                'excl. 0 (QB only)' if sig_qb else 'incl. 0')
        print(f'  vs {name:26s} dr={dr:+.4f}  QB[{qlo:+.3f},{qhi:+.3f}] '
              f'season[{slo:+.3f},{shi:+.3f}]  {flag}')
        L.append(f'| vs {name} | {dr:+.4f} | [{qlo:+.3f}, {qhi:+.3f}] | '
                 f'[{slo:+.3f}, {shi:+.3f}] | {flag} |')
    L.append('')

    print('\n--- probabilistic scoring (full predictive interval) ---')
    L.append('## Probabilistic scoring — full predictive intervals\n')
    L.append('Variance = state + skill-transition + target sampling noise '
             f'(skill_change_var={params["predictive_interval"]["skill_change_var"]:.5f}, '
             f'play_noise_var={params["predictive_interval"]["play_noise_var"]:.3f}, '
             'both fit on 2006-2018 only).\n')
    L.append('| Forecast mean | cov50 | cov80 | cov90 | PIT KS | CRPS | NLL | mean sd |')
    L.append('|---|---|---|---|---|---|---|---|')
    for name, col in [('LEAF v3.4 (fused)', 'leaf_v34'),
                      ('V3 informed state (what the dashboard actually plots)', 'k_informed')]:
        sc, sd = prob_scores(d, d[col], params)
        print(f'  {name:52s} cov80={sc["cov80"]:.1%} CRPS={sc["CRPS"]:.4f} '
              f'NLL={sc["NLL"]:+.3f} KS={sc["PIT_KS"]:.3f}')
        L.append(f'| {name} | {sc["cov50"]:.1%} | {sc["cov80"]:.1%} | {sc["cov90"]:.1%} '
                 f'| {sc["PIT_KS"]:.3f} | {sc["CRPS"]:.4f} | {sc["NLL"]:+.3f} | {sd.mean():.4f} |')

    # state-only comparison to document the v3 defect
    z = 1.2816
    sd_state = np.sqrt(d['state_var'])
    cov_state = float(((d['target'] >= d['k_informed'] - z * sd_state)
                       & (d['target'] <= d['k_informed'] + z * sd_state)).mean())
    L.append(f'| _state-variance only (v3 behaviour, for reference)_ | — | {cov_state:.1%} | — | — | — | — | {sd_state.mean():.4f} |')
    print(f'  {"state-only (v3 behaviour)":52s} cov80={cov_state:.1%}')
    L.append('')

    L.append('## Per-season breakdown (LEAF v3.4)\n')
    L.append('| Season | n | r | RMSE | cov80 |')
    L.append('|---|---|---|---|---|')
    for s, g in d.groupby('target_season'):
        sc, _ = prob_scores(g, g[PRIMARY], params)
        L.append(f'| {int(s)} | {len(g)} | {g[PRIMARY].corr(g["target"]):+.3f} '
                 f'| {np.sqrt(((g[PRIMARY]-g["target"])**2).mean()):.4f} | {sc["cov80"]:.1%} |')
    L.append('')

    # ---- headline verdict, derived from the numbers just computed ----
    r_fused = d['leaf_v34'].corr(d['target'])
    r_inf = d['k_informed'].corr(d['target'])
    dr_inf = r_fused - r_inf
    qlo_i, qhi_i = paired_boot(d, 'leaf_v34', 'k_informed', 'passer_player_id')
    slo_i, shi_i = paired_boot(d, 'leaf_v34', 'k_informed', 'target_season')
    sc_f, _ = prob_scores(d, d['leaf_v34'], params)
    verdict = [
        '## Headline verdict\n',
        f'1. **Interval calibration is repaired.** Nominal 80% coverage moves from '
        f'{cov_state:.1%} (state variance only, the v3 behaviour) to '
        f'{sc_f["cov80"]:.1%} with the full predictive interval. PIT KS = '
        f'{sc_f["PIT_KS"]:.3f}. Slight over-coverage remains; the interval is now '
        'conservative rather than badly overconfident.\n',
        f'2. **The fusion layer no longer earns its place on ranking.** With the '
        f'label leakage removed, LEAF v3.4 fused (r = {r_fused:+.4f}) ranks BELOW '
        f'the un-fused informed state (r = {r_inf:+.4f}); Δr = {dr_inf:+.4f}, '
        f'95% CI [{qlo_i:+.3f}, {qhi_i:+.3f}] clustered by QB and '
        f'[{slo_i:+.3f}, {shi_i:+.3f}] clustered by season — the season-clustered '
        'interval excludes zero. Part of v3\'s apparent fusion benefit came from '
        f'the {params["fusion"]["n_excluded_for_target_leakage"]} training pairs '
        'whose targets reached into the frozen era.\n',
        '3. **Fused still wins on level, not order.** It has the best RMSE, MAE and '
        'CRPS of every predictor scored here, consistent with v3\'s finding that '
        'the machinery earns its keep on calibration rather than ranking.\n',
        '4. **Do not compare these numbers directly to v3\'s published table.** The '
        'population changed (regular season only, QB passers only), so the targets '
        'themselves differ. This document re-certifies the corrected pipeline; it '
        'is not a v3-vs-v3.4 horse race on identical data.\n',
        '### Consequence for Phase 2\n',
        'The exporter labels `leaf_v3` as "leaf_rating" while the dashboard forecasts '
        'from `k_informed`. On this evidence the dashboard\'s choice of mean is the '
        'better ranking predictor, but the mismatch is undocumented and unevaluated. '
        'Phase 2 must make the deployed mean explicit, versioned, and backtested '
        'along the exact deployed path.\n',
    ]
    L = L[:3] + verdict + L[3:]

    out = ROOT / 'docs' / 'LEAF_V34_RECERTIFICATION.md'
    out.write_text('\n'.join(L), encoding='utf-8')
    d.to_csv(PROD / 'leaf_v34_t1_eval_pairs.csv', index=False, float_format='%.6f')
    print(f'\n[OK] -> {out}')


if __name__ == '__main__':
    main()
