"""
Write docs/LEAF_V34_MANIFEST.md: SHA-256 hashes, sizes and row counts for every
tracked v3.4 artifact, so a checkout can be verified byte-for-byte.

Usage: python scripts/v3_4/make_manifest.py
"""

import hashlib
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent
PROD = ROOT / 'data' / 'production'

ARTIFACTS = [
    (PROD / 'qb_games_base_v34.csv', 'versioned base dataset (REG + QB only)'),
    (PROD / 'qb_games_base_v34_dropreport.csv', 'rows excluded, with reasons'),
    (PROD / 'leaf_v34_ratings.csv', 'per-QB-game walk-forward ratings'),
    (PROD / 'leaf_v34_params.json', 'all fitted hyperparameters + interval calibration'),
    (PROD / 'leaf_v34_fusion_pairs.csv', 'fusion pairs with target provenance'),
    (PROD / 'leaf_v34_t1_eval_pairs.csv', 'frozen-era T1 evaluation pairs'),
]


def sha256(path, chunk=1 << 20):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        while True:
            b = f.read(chunk)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def main():
    lines = ['# LEAF v3.4 Artifact Manifest\n',
             'Generated by `scripts/v3_4/make_manifest.py`. Every artifact below is '
             'tracked in Git so the v3.4 baseline is reproducible from a clean '
             'checkout without re-downloading nflverse data.\n',
             '| Artifact | Size | Rows | SHA-256 | Contents |',
             '|---|---|---|---|---|']
    missing = []
    for path, desc in ARTIFACTS:
        if not path.exists():
            missing.append(path.name)
            lines.append(f'| `{path.name}` | — | — | MISSING | {desc} |')
            continue
        size = path.stat().st_size
        digest = sha256(path)
        try:
            with open(path, 'r', encoding='utf-8', errors='replace') as f:
                rows = max(sum(1 for _ in f) - 1, 0) if path.suffix == '.csv' else '—'
        except OSError:
            rows = '—'
        lines.append(f'| `{path.name}` | {size/1048576:.2f} MB | {rows} '
                     f'| `{digest}` | {desc} |')
        print(f'  {path.name:38s} {digest[:16]}...  {size/1048576:6.2f} MB')

    out = ROOT / 'docs' / 'LEAF_V34_MANIFEST.md'
    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'\n[OK] -> {out}')
    if missing:
        print('[WARN] missing artifacts: ' + ', '.join(missing))
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
